/**
 * delivery-evidence/1 conformance kit.
 *
 * The vendored 89-vector kit lives in ./vectors (kit root: kit.json, context/,
 * vectors/accept/, vectors/reject/) and is regenerated byte-identically by
 * ./generate.ts. The kit runner (unit + integration modes) arrives in U4/U8.
 */

export const PACKAGE_NAME = "@delivery-harness/conformance";
