/**
 * delivery-evidence/1 conformance kit.
 *
 * The vendored 89-vector kit lives in ./vectors (kit root: kit.json, context/,
 * vectors/accept/, vectors/reject/) and is regenerated byte-identically by
 * ./generate.ts. The runner below drives it in unit mode — the manifest-decidable
 * vectors, judged by the pure kernel validator under a configuration the caller
 * supplies. Integration mode, which adds the five recorder-dependent vectors,
 * arrives with the recorder.
 */

export const PACKAGE_NAME = "@delivery-harness/conformance";

export {
  RECORDER_DEPENDENT_VECTORS,
  compareOutcome,
  describeFailures,
  evaluateVector,
  kitRoot,
  loadKitEnvironment,
  loadKitIndex,
  loadKitVectors,
  runKitUnitMode,
  type DeferredVector,
  type KitEnvironment,
  type KitExpectation,
  type KitIndex,
  type KitIndexEntry,
  type KitOutcome,
  type KitOutcomeStatus,
  type KitRunOptions,
  type KitRunResult,
  type KitVector,
  type ValidatorOutcome,
} from "./runner.ts";
export { validateAgainstSchema, type SchemaViolation } from "./json-schema.ts";
