/** Compatibility exposure; execution is shared by all product callers. */
export {
  DELIVERY_PROVIDER_RAILS_VERSION,
  type ProviderRailNegotiate,
  type ProviderRailNegotiation,
  type ProviderRailRequest,
  type ProviderRailProgress,
  type ProviderRailEvidence,
  type ProviderRailBlocker,
  type ProviderRailTerminal,
  type ProviderRailCancel,
  type ProviderRailEvent,
  type ProviderRailMessage,
  type ProviderRailConsumption,
  type ConsumeProviderRailOptions,
  consumeProviderRailMessages,
  type ProviderRailSession,
  type OpenProviderRailProcessInput,
  openProviderRailProcess,
  type ProviderRailAttemptInput,
  type ProviderRailAttemptOptions,
  type ProviderRailInvocationResult,
  invokeProviderRail,
} from "@agent-delivery-harness/kernel";
