import { execFile } from "node:child_process";
import { mkdtemp, mkdir, writeFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { promisify } from "node:util";
import { expect, it } from "vitest";
import { GATE_STRUCTURAL_FINDING_CODES } from "./blockers.ts";
import { defineHarnessConfig } from "./config.ts";
import { captureCheckBindings, captureScopedCheckInputs } from "./checks.ts";
import { createCandidateCapture } from "./candidate.ts";
import { computeDeliverableIdentity } from "./identity.ts";
import { publishPreparationReceipt, computePreparationFingerprint } from "./preparation.ts";
import { resolveRecordStorage } from "./records.ts";
import { createArtifactsPort } from "./artifacts.ts";
import { submitManifest } from "./recorder.ts";
import { evaluateGate } from "./evaluator.ts";
import { bindingOf, buildDeliveryRecord, verifyDeliveryRecord } from "./delivery-record.ts";
import { capturePortableEvidenceContext, repositoryEvidenceReader } from "./portable-evidence.ts";
import { digestCanonical, sha256Hex } from "./digest.ts";
import type { ScopedCheckPlan, ScopedCheckAttempt } from "./records.types.ts";

const exec = promisify(execFile);
it("replans a real Git candidate, reuses scoped proof, and keeps final-record binding strict", async () => {
  const rootDir = await mkdtemp(path.join(tmpdir(), "scoped-kernel-"));
  try {
    const git = async (...args: string[]) => (await exec("git", args, { cwd: rootDir })).stdout.trim();
    await git("init", "-q"); await git("config", "user.name", "Fixture"); await git("config", "user.email", "fixture@example.invalid");
    await mkdir(path.join(rootDir, "tests"));
    await writeFile(path.join(rootDir, "source.ts"), "app"); await writeFile(path.join(rootDir, "tests/app.test.ts"), "test");
    await writeFile(path.join(rootDir, "harness.config.ts"), "export default {};");
    await writeFile(path.join(rootDir, "report.html"), "report");
    await git("add", "."); await git("-c", "commit.gpgsign=false", "commit", "-qm", "base"); await git("branch", "base");
    const scope = { version: "scoped-check/1" as const, files: ["source.ts", "absent.json"], memberships: ["tests/"], tests: ["tests/app.test.ts"], cwd: ".", profile: "local", environment: [] };
    const check = { command: [process.execPath, "-e", "if(require('fs').readFileSync('source.ts','utf8')!=='app')process.exit(1)"] as [string, ...string[]], timeoutMs: 5000, scope };
    const config = defineHarnessConfig({ gateId: "fixture.gate", baseRef: "base", acceptedEnvelopeSpecs: ["delivery-evidence/1"], identityVersions: ["fixture/v1"], computingIdentityVersion: "fixture/v1", reviewNeutral: [{ prefix: "delivery/records/" }], recordNeutral: [{ prefix: "delivery/records/" }], pathClassification: { generated: [], test: [{ kind: "glob", value: "**/*.test.ts" }], lockfile: [] }, sensitivePaths: [], activationThreshold: 1, agentEnvSignals: [], ciPolicies: [], ciPolicyEnvKey: "FIXTURE_CI", deliveryRecordPath: "delivery/records/record.json", preparationWiringPaths: ["harness.config.ts"], preparationCommands: [],
      providers: [{ id: "check.app", findingCodes: [], check }], obligations: [{ id: "tests.green", activation: { kind: "always" }, freshness: "exact_candidate", minimumAttestationLevel: "self", ciDelegationPolicyIds: [], remediation: { default: [{ id: "repair", kind: "manual_action", summary: "Repair the check." }] }, waivableCodes: [], nonWaivableCodes: [...GATE_STRUCTURAL_FINDING_CODES], providers: ["check.app"], acceptedPayloadSpecs: ["checks.passed/1"], providerPolicy: "all", allowedResolutionKinds: ["satisfied_evidence", "not_applicable"], humanWaiverAllowed: false }] });
    const workspaceId = (await resolveRecordStorage(rootDir)).workspaceId;
    const captureCandidate = createCandidateCapture({ rootDir, config, workspaceId, computeIdentity: computeDeliverableIdentity });
    const capture = async () => { const r = await captureCandidate(); if (!r.ok) throw new Error(JSON.stringify(r)); return r.candidate; };
    const candidate = await capture();
    const inputs = async (tree: string) => captureScopedCheckInputs(scope, { ...check, runtimeDigest: digestCanonical(process.version), dependencyDigest: digestCanonical("no-dependencies"), policyDigest: digestCanonical("policy"), releaseDigest: digestCanonical(null), environment: {}, credentialIdentity: () => null,
      listFiles: async () => (await git("ls-tree", "-r", "--name-only", tree)).split("\n"), readFile: async file => { try { return Buffer.from((await exec("git", ["show", `${tree}:${file}`], { cwd: rootDir })).stdout); } catch { return null; } } });
    const originalInputs = await inputs(candidate.treeSha);
    const attempt: ScopedCheckAttempt = { version: "scoped-attempt/1", providerId: "check.app", attemptId: "attempt-1", generation: 1, inputDigest: originalInputs.inputDigest, profileDigest: digestCanonical("local"), status: "passed", origin: { candidate: bindingOf(candidate), runId: "run-1" } };
    const makePlan = (c: typeof candidate, inputDigest = originalInputs.inputDigest, attempts = [attempt]): ScopedCheckPlan => ({ version: "scoped-plan/1", candidate: bindingOf(c), selectionDigest: digestCanonical([{ id: "check.app", check }]), checks: { "check.app": { inputDigest, profileDigest: attempt.profileDigest, reusable: true, attempts } } });
    const plan = makePlan(candidate);
    await publishPreparationReceipt(rootDir, { config, candidate });
    await exec(check.command[0], check.command.slice(1), { cwd: rootDir });
    const bindings = await captureCheckBindings(rootDir, config, candidate, { scopedPlan: plan });
    const payload = { verdict: "green", exitCode: 0, binding: bindings["check.app"] };
    await mkdir(path.join(rootDir, ".git/artifacts"));
    const artifacts = createArtifactsPort({ runRootBase: path.join(rootDir, ".git/artifacts") });
    const allocation = await artifacts.allocateRunRoot({ providerId: "check.app", runId: "run-1" });
    if (!allocation.ok) throw new Error("artifact allocation");
    const terminal = JSON.stringify({ providerId: "check.app", runId: "run-1", finalPassId: "pass-1", ...payload });
    const manifest = { spec: "delivery-evidence/1", provider: { id: "check.app", runId: "run-1", finalPassId: "pass-1" }, candidate: { vcs: "git", treeSha: candidate.treeSha, headSha: candidate.headSha, deliverable: candidate.deliverable, base: candidate.base, workspaceId }, runHistory: [{ preparedTreeSha: candidate.treeSha, evaluatedInPassId: "pass-1" }], artifacts: [{ path: "check-result.json", role: "check-result", sha256: sha256Hex(terminal) }], attestation: { level: "self", signatures: [] }, recordedAt: "2026-09-12T00:00:00Z", claims: [{ obligation: "tests.green", payloadSpec: "checks.passed/1", payload }] };
    const manifestPath = path.join(allocation.runRoot.path, "manifest.json");
    await artifacts.writeTextFile(path.join(allocation.runRoot.path, "check-result.json"), terminal); await artifacts.writeTextFile(manifestPath, JSON.stringify(manifest));
    const submitted = await submitManifest({ rootDir, config, manifestPath }, { captureCandidate, artifacts, scopedPlan: plan });
    expect(submitted, JSON.stringify(submitted)).toMatchObject({ status: "accepted" });
    if (submitted.status !== "accepted") throw new Error("submission");
    await writeFile(path.join(rootDir, "report.html"), "changed report"); await git("add", "."); await git("-c", "commit.gpgsign=false", "commit", "-qm", "report");
    const current = await capture();
    expect(current.treeSha).not.toBe(candidate.treeSha);
    expect((await inputs(current.treeSha)).inputDigest).toBe(originalInputs.inputDigest);
    await expect(captureCheckBindings(rootDir, config, current, { scopedPlan: plan })).rejects.toThrow();
    const currentBindings = await captureCheckBindings(rootDir, config, current, { scopedPlan: makePlan(current) });
    const projection = { relevantLineCount: 1, relevantPaths: ["report.html"], excludedPaths: [], binaryPaths: [], sensitivePathIds: [], hasRelevantBinaryChange: false, hasRelevantZeroLineChange: false, changedEntryCount: 1 };
    const context = { kind: "unknown" as const, reason: "noninteractive_unrecognized" as const };
    const records = submitted.records.map(r => r.record);
    const decision = evaluateGate({ config, candidate: current, projection, context, records, checkBindings: currentBindings });
    expect(decision.admitted).toBe(true);
    const evidenceContext = await capturePortableEvidenceContext(config, repositoryEvidenceReader(rootDir, artifacts), await computePreparationFingerprint(rootDir, config));
    const built = buildDeliveryRecord({ config, decision, evidenceRecords: records, context: evidenceContext });
    if (!built.ok) throw new Error(JSON.stringify(built));
    const verified = verifyDeliveryRecord(config, built.record, { deliverableDigest: current.deliverable.digest, identityToken: current.deliverable.identity }, current.base, { evidenceContext, projection, executionContext: context, checkBindings: currentBindings });
    expect(verified, JSON.stringify(verified)).toMatchObject({ ok: true });
    expect(verifyDeliveryRecord(config, built.record, { deliverableDigest: candidate.deliverable.digest, identityToken: candidate.deliverable.identity }, current.base, { evidenceContext, projection, executionContext: context, checkBindings: currentBindings }).ok).toBe(false);
    const failed = { ...attempt, attemptId: "attempt-2", generation: 2, status: "failed" as const };
    expect(await captureCheckBindings(rootDir, config, current, { scopedPlan: makePlan(current, originalInputs.inputDigest, [failed, attempt]) })).toEqual({});
    // A current plan can add an obligation without changing an existing result's identity.
    const sibling = { id: "check.docs", findingCodes: [], check: { ...check, scope: { ...scope, files: ["report.html"] } } };
    const expanded = defineHarnessConfig({ ...config, providers: [...config.providers, sibling], obligations: [{ ...config.obligations[0]!, providers: ["check.app", "check.docs"] }] });
    const expandedPlan: ScopedCheckPlan = { ...makePlan(current), selectionDigest: digestCanonical(expanded.providers.map(p => ({ id: p.id, check: p.check }))), checks: { ...makePlan(current).checks, "check.docs": { inputDigest: digestCanonical("docs"), profileDigest: attempt.profileDigest, reusable: true, attempts: [] } } };
    const expandedBindings = await captureCheckBindings(rootDir, expanded, current, { scopedPlan: expandedPlan });
    expect(expandedBindings["check.app"]).toEqual(currentBindings["check.app"]);
    expect(evaluateGate({ config: expanded, candidate: current, projection, context, records, checkBindings: expandedBindings }).admitted).toBe(false);
    // Independent portable integrity and trust controls remain active for scoped records.
    const verify = (record = built.record, checkBindings = currentBindings, currentContext = evidenceContext) => verifyDeliveryRecord(config, record, { deliverableDigest: current.deliverable.digest, identityToken: current.deliverable.identity }, current.base, { evidenceContext: currentContext, projection, executionContext: context, checkBindings });
    const tampered = structuredClone(built.record);
    const retained = tampered.claims[0]!.evidence!;
    if (retained.resolution.kind !== "evidence") throw new Error("fixture");
    (retained.resolution.portable!.artifacts as Record<string, string>)["check-result.json"] = Buffer.from("tampered").toString("base64");
    expect(verify(tampered).ok).toBe(false);
    expect(verify(built.record, {}).ok).toBe(false);
    expect(verify(built.record, currentBindings, { ...evidenceContext, release: { releaseId: "incompatible" } }).ok).toBe(false);
    expect(verify(built.record, { "check.app": { ...currentBindings["check.app"]!, scopedProfileDigest: digestCanonical("hosted") } }).ok).toBe(false);
    await writeFile(path.join(rootDir, "source.ts"), "broken"); await git("add", "."); await git("-c", "commit.gpgsign=false", "commit", "-qm", "source change");
    const changed = await capture();
    const changedInputs = await inputs(changed.treeSha);
    expect(changedInputs.inputDigest).not.toBe(originalInputs.inputDigest);
    expect(await captureCheckBindings(rootDir, config, changed, { scopedPlan: makePlan(changed, changedInputs.inputDigest) })).toEqual({});
  } finally { await rm(rootDir, { recursive: true, force: true }); }
}, 30_000);
